### PR TITLE
Added original names and automatic timer

### PR DESCRIPTION
**Pull request by AngelCasillas01**
test this because i made it with an iPad, with github editor :P

### CODE REVIEW

**Comment by AngelCasillas01** [comment]
Omfg sorry for that commit name;(

**Comment by AngelCasillas01** [comment]
#10

**Comment by vYuri** [comment]
i'll test this

**Comment by vYuri** [comment]
Good Job

**Comment by AngelCasillas01** [comment]
Oh, sorry, I thought it was 1h by the objective, i'm sorry ;(

**Pull request merged**
